print('Hello World!', end='')
print('Hello Again!', end='')
print('I like typing this.')
print('This is fun.')
print('Yay! Printing.')
print("I'd much rather you 'not'.")
# print('\n')
# print('I "said" do not touch this.')
